version: "3"
services:
  mongo:
    image: mongo:4
    restart: always
    environment:
      - MONGODB_INITDB_DATABASE=
  app:
    build: .
    restart: always
    ports:
      - 17594:8080
    links:
      - mongo:mongo
    volumes:
      - ./config.toml:/usr/local/src/app/config.toml
